# Generated by Django 3.1.2 on 2022-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convtexte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convtexte',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
