# Generated by Django 3.1.2 on 2022-04-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convtexte', '0002_convtexte_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convtexte',
            name='status',
        ),
    ]
